import { FormEvent, useEffect, useState } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { LockKeyhole, ShieldCheck, UserRound } from 'lucide-react';
import { Alert } from '../components/ui/Alert';
import { Button } from '../components/ui/Button';
import { Card, CardContent } from '../components/ui/Card';
import { Input } from '../components/ui/Input';
import { LoadingScreen } from '../components/ui/LoadingScreen';
import { useAuth } from '../context/AuthContext';
import { isSupabaseConfigured } from '../lib/supabase';
import { cn, getErrorMessage } from '../lib/utils';

type LoginMode = 'admin' | 'employee';

type LocationState = {
  from?: {
    pathname?: string;
  };
};

export function LoginPage() {
  const { loading, profile, signInAdmin, signInEmployee } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [mode, setMode] = useState<LoginMode>('admin');
  const [adminEmail, setAdminEmail] = useState('');
  const [adminPassword, setAdminPassword] = useState('');
  const [employeeUsername, setEmployeeUsername] = useState('');
  const [employeePassword, setEmployeePassword] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const redirectTo = (location.state as LocationState | null)?.from?.pathname;

  useEffect(() => {
    setError('');
  }, [mode]);

  if (loading) return <LoadingScreen />;

  if (profile) {
    return <Navigate to={profile.role === 'admin' ? '/admin' : '/employee'} replace />;
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitting(true);
    setError('');

    try {
      const nextProfile =
        mode === 'admin'
          ? await signInAdmin(adminEmail.trim(), adminPassword)
          : await signInEmployee(employeeUsername.trim().toUpperCase(), employeePassword);

      navigate(redirectTo || (nextProfile.role === 'admin' ? '/admin' : '/employee'), { replace: true });
    } catch (caughtError) {
      setError(getErrorMessage(caughtError, 'Login failed. Please check your credentials.'));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="min-h-screen bg-slate-950 px-4 py-8 text-white sm:px-6 lg:px-8">
      <div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl items-center">
        <div className="grid w-full gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
          <div className="space-y-8">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm font-semibold text-slate-200">
              <ShieldCheck className="h-4 w-4" aria-hidden="true" />
              Secure attendance management
            </div>
            <div>
              <h1 className="max-w-3xl text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
                Attendance tracking built for controlled company access.
              </h1>
              <p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">
                Admins create every employee account. Employees sign in only with the username and password generated by the company.
              </p>
            </div>
            <div className="grid gap-4 sm:grid-cols-3">
              {['No public signup', 'Role-based security', 'Supabase RLS'].map((item) => (
                <div key={item} className="rounded-2xl border border-white/10 bg-white/10 p-4">
                  <p className="text-sm font-bold text-white">{item}</p>
                </div>
              ))}
            </div>
          </div>

          <Card className="border-white/10 bg-white text-slate-950 shadow-2xl">
            <CardContent className="p-6 sm:p-8">
              <div className="mb-7 text-center">
                <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-950 text-white">
                  <LockKeyhole className="h-7 w-7" aria-hidden="true" />
                </div>
                <h2 className="mt-4 text-2xl font-bold">Sign in to AMS</h2>
                <p className="mt-1 text-sm text-slate-500">Choose the correct access type. There is no self-registration.</p>
              </div>

              {!isSupabaseConfigured ? (
                <Alert tone="info" className="mb-5">
                  Supabase environment variables are not configured yet. Add this project's values to <strong>.env</strong> before logging in.
                </Alert>
              ) : null}

              <div className="mb-6 grid grid-cols-2 rounded-2xl bg-slate-100 p-1">
                <button
                  className={cn(
                    'rounded-xl px-4 py-2.5 text-sm font-bold transition',
                    mode === 'admin' ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-500 hover:text-slate-900'
                  )}
                  type="button"
                  onClick={() => setMode('admin')}
                >
                  Admin
                </button>
                <button
                  className={cn(
                    'rounded-xl px-4 py-2.5 text-sm font-bold transition',
                    mode === 'employee' ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-500 hover:text-slate-900'
                  )}
                  type="button"
                  onClick={() => setMode('employee')}
                >
                  Employee
                </button>
              </div>

              {error ? <Alert tone="error" className="mb-5">{error}</Alert> : null}

              <form className="space-y-4" onSubmit={handleSubmit}>
                {mode === 'admin' ? (
                  <>
                    <Input
                      label="Admin email"
                      type="email"
                      placeholder="admin@company.com"
                      value={adminEmail}
                      onChange={(event) => setAdminEmail(event.target.value)}
                      required
                    />
                    <Input
                      label="Admin password"
                      type="password"
                      placeholder="Enter admin password"
                      value={adminPassword}
                      onChange={(event) => setAdminPassword(event.target.value)}
                      required
                    />
                  </>
                ) : (
                  <>
                    <Input
                      label="Employee username"
                      placeholder="EMP001"
                      value={employeeUsername}
                      onChange={(event) => setEmployeeUsername(event.target.value.toUpperCase())}
                      required
                      helperText="Use the username provided by your admin. Email login is disabled for employees."
                    />
                    <Input
                      label="Employee password"
                      type="password"
                      placeholder="Enter generated password"
                      value={employeePassword}
                      onChange={(event) => setEmployeePassword(event.target.value)}
                      required
                    />
                  </>
                )}

                <Button className="w-full" size="lg" type="submit" loading={submitting} leftIcon={<UserRound className="h-5 w-5" />}>
                  Sign in as {mode}
                </Button>
              </form>

              <p className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">
                Employees cannot register, reset passwords, or change roles. Contact an admin for account changes.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
